import {
  InterfaceService,
  InterfaceEmailRegistered,
  InterfaceAuthLogin,
  InterfaceUserCofirmed,
  InterfaceAuthConfirmUser,
  InterfaceValidToken,
  InterfaceChangedPassword,
  InterfaceDataCategory,
  InterfaceDataCategoryPlus,
  InterfaceGetManyCategories,
  InterfaceMessageResponse,
  InterfaceDataType,
  InterfaceDataTypePlus,
  InterfaceGetManyTypes,
  InterfaceDataOffer,
  InterfaceGetManyOffers,
  InterfaceDataProduct,
  InterfaceGetManyProducts,
} from "./service.interface";

export {
  InterfaceService,
  InterfaceEmailRegistered,
  InterfaceAuthLogin,
  InterfaceUserCofirmed,
  InterfaceAuthConfirmUser,
  InterfaceValidToken,
  InterfaceChangedPassword,
  InterfaceDataCategory,
  InterfaceDataCategoryPlus,
  InterfaceGetManyCategories,
  InterfaceMessageResponse,
  InterfaceDataType,
  InterfaceDataTypePlus,
  InterfaceGetManyTypes,
  InterfaceDataProduct,
  InterfaceGetManyProducts,
  InterfaceDataOffer,
  InterfaceGetManyOffers,
};
